### ISSUE TITLE
[1.7] World Generation issue

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#260] opened 2018-03-11 23:52 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
ExtraPlanets biomes spawning on Earth.

### Steps to Reproduce Issue
1. Install latest version of Extraplanets and galacticraft.
2. Create a new world and do some exploring. It is rare to find it, I noticed it because I spawned next to an oberonLargeMountain biome.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 
![2018-03-11_23 51 14](https://user-images.githubusercontent.com/19786108/37260118-381892a4-2587-11e8-8b46-c1847f2f4aa5.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.7.10-1.9.9]

**Where did this bug happen:** I have seen this in previous versions on multiplayer, however in this version I havnt been able to test multiplayer, so singleplayer for this version as far as I know. In previous versions I have seen neptune, jupiter and saturn spawning, not just oberon.

### Additional Information
The only thing I can think of is Biome ID conflicts, I will go through config files checking these now.

**Comment by MJRLegends** [comment] 2018-03-12 00:02
Which other mods do you have?

**Comment by Breadabix** [comment] 2018-03-12 00:06
Roughly another 250 :/ Im having a look at the obvious ones atm, but will have to wait till after school tomorrow to have a look through everything

**Comment by MJRLegends** [comment] 2018-03-12 00:06
do you have biomes o plenty or a mod that adds biomes?

**Comment by Breadabix** [comment] 2018-03-12 00:08
I dont have biomes o plenty or biomes XL, or any variants of those mods. I have just noticed I have antiIDconflict, with it set to crash with any biome ID conflicts, so from the fact its not crashing on loadup i dont think there is any biome conflicts

**Comment by MJRLegends** [comment] 2018-03-12 00:10
Oberon Large Mountain Biome ID is default at 193 which not a minecraft biome so either something such as your antiIDconflict is not working or you have another mod with 193 biome id assigned to it

**Comment by Breadabix** [comment] 2018-03-12 00:13
It registers thaumcrafts magical forest biome as 193, I dont think it crashed as the mod doesnt seem to be compatable with extraplanets, its not listing the biomes or dimensions from EP atleast

**Comment by MJRLegends** [comment] 2018-03-12 00:15
Every mod should have ability to change the id from the configs, you can do this from the ExtraPlanets one and Galacticraft for sure. Due to this is just a conflict and can be fixed through config options added to ExtraPlanets for this purpose and its not a bug. i will close this issue :P 

If you need anymore help please post here

**Closed by MJRLegends** 2018-03-12 00:15 UTC
Labels: 1.7.10, compatibility issue, more information needed

**Comment by MJRLegends** [comment] 2018-03-12 00:19
Looking at the thaumcrafts source code, thaumcrafts has config options for changing biome ids too

they use the following, either change them in thaumcrafts config or ExtraPlanets for the ones conflicting

biomeTaintID = 192
biomeMagicalForestID = 193
biomeEerieID = 194
biomeEldritchID = 195

**Comment by MJRLegends** [comment] 2018-03-12 00:20
ExtraPlanets uses all the thaumcrafts ids so change all of them

**Comment by Breadabix** [comment] 2018-03-12 00:28
Saw this, might also be issues with other mods. Ill have a full look tomorrow and post here for other people who might have the same issue.

**Comment by MJRLegends** [comment] 2018-03-12 00:30
i doubt theres others mods but its the purpose of config options for biome ids :D

**Comment by Breadabix** [comment] 2018-03-12 16:41
Would just like to point out some biome ID conflicts with vanilla minecraft: https://gyazo.com/d34ced73b306b5688a7f2fbe0cfd4b69
149 and 155 are both used in vanilla MC and are default configs for ExtraPlanets.

**Comment by MJRLegends** [comment] 2018-03-12 19:41
Thanks they are very rare biomes anyways so i doubt anyone would see them, and in the years of this mod being released its only now someone including me has noticed it haha

I will fix this though
