### ISSUE TITLE
[1.8+] Rocket Launch Pad issue

### ISSUE THREAD

**Issue by artdude543** [MJRLegends/ExtraPlanets#318] opened 2018-06-05 20:55 UTC
Hello, I come to thee to post a dupe issue, which was posted on the SevTech: Ages tracker. I did see a similar issue posted last year on the tracker. But I thought to post a new one as the linked issue contains a decent amount of data and videos on the various dupe issues.

Minecraft version: 1.12.2
ExtraPlanets: 0.3.3
Galacticraft version: 4.0.1.176

All details and video can be found here: DarkPacks/SevTech-Ages#2750

**Comment by MJRLegends** [comment] 2018-06-11 19:13
@artdude543 Please get them to test with new version as im unable to reproduce it from my first tests for this issue

**Comment by MJRLegends** [comment] 2018-06-11 19:16
Im able to reproduce it, i will see what i can do it fix this

**Comment by MJRLegends** [comment] 2018-06-11 21:28
Updates will be released some time this week

**Comment by artdude543** [comment] 2018-06-11 21:29
Thank you for the fix! 🤗

**Comment by MJRLegends** [comment] 2018-06-11 21:32
@artdude543 No problem im not happy with the clips tho and the fact the streamer decided to show it on a stream and acted in way like he wanted people to use the bug. But yolo :P.

**Comment by artdude543** [comment] 2018-06-11 21:43
Yeah; not a fan of the way it was done either. But at least someone reported it I guess. Otherwise would be hidden with all the clips on Twitch xD

**Comment by MJRLegends** [comment] 2018-06-15 23:03
Updates are coming out as we speak

**Closed by MJRLegends** 2018-06-15 23:03 UTC
Labels: 1.10.2, 1.11.2, 1.12.2, 1.8.9, bug, fixed in next update (will close issue when update is out)
