### ISSUE TITLE
Broken entity & mob models/textures on non-native dimensions

### ISSUE THREAD

**Issue by TheRealDannyyy** [MJRLegends/ExtraPlanets#408] opened 2019-03-08 20:07 UTC
### Description of Issue
Entity and mob models/textures seem to be bugged on all dimension/planets except the native ones. 
I have no clue what the cause of this could be but removing any visual mods such as _optifine_ and custom resourcepacks, did not fix the issue. Below you can find the latest log and screenshots of the issue.

### Steps to Reproduce Issue
1. Load up most recent version of galacticraft, extraplanets and the required library
2. Visit any dimension that isn't native to the game
3. Notice entities and mobs with broken models/textures

**Crash log/Log (if applicable):** [Pastebin Link](https://pastebin.com/QtRDa6gQ)

**Screenshots (if applicable):** 
![Example 1](https://user-images.githubusercontent.com/15656049/54052460-c1b93480-41e4-11e9-9dad-a7d462385c08.jpg)
![Example 2](https://user-images.githubusercontent.com/15656049/54052461-c1b93480-41e4-11e9-8748-1d42849b58eb.jpg)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
- MinecraftForge v14.23.5.2815
- ExtraPlanets-1.12.2-0.4.9
- Galacticraft-Planets-1.12.2-4.0.2.190
- MicdoodleCore-1.12.2-4.0.2.190
- ExtraPlanets-1.12.2-0.4.9
- MJRLegendsLib-1.12.2-1.1.8
- jei_1.12.2-4.15.0.269

(_Server is using exactly the same versions._)

**Where did this bug happen:** Dedicated _Nitrado_ server with connected clients.

### Additional Information
I could only reproduce this using extra planets and the required library, the standalone galacticraft mod works fine, which lead to my conclusion that extraplanets might be at fault.

**Comment by MJRLegends** [comment] 2019-03-08 21:25
ok so the only thing i see wrong the the arrows have a black box on them, the mobs took as intended??

**Comment by TheRealDannyyy** [comment] 2019-03-08 21:44
![Example 3](https://user-images.githubusercontent.com/15656049/54057431-3eeba600-41f3-11e9-88fb-9faa7ede0205.jpg)
Players lose their transparency for both their suit and items in their hand(s). For mobs it's worse, their entire head occasionally turns invisible or they also lose their transparency.

Two more things I've noticed is that this only occurs at certain distances, so it might be related to how the game is culling objects. I also noticed a clear memory leak, which results in javaw.exe using up to 5gb!

**Comment by MJRLegends** [comment] 2019-03-08 21:46
Have you tried the sensor glasses are i believe they will do the same which makes this not my issue, as the space suit just uses some sensor glasses feature...

**Comment by MJRLegends** [comment] 2019-03-08 21:51
Just tried the sensor glasses from Galacticraft (without ExtraPlanets installed) myself and the black box around the arrow is 
![](https://i.gyazo.com/9281639ba4bdf321ca695dab4db05b64.png)
so i delaring this to be a galacticraft feature as im only using the sensor glasses mob render feature with the space suit by using there ISensorGlassesArmor interface. Which then a module can be installed on the suite to get the other sensor glasses feature such as ore finding..

Please report to Galacticraft devs which the explaining the sensor glasses has the bug. once that is fixed space suit uses of  sensor glasses features will be fixed

**Closed by MJRLegends** 2019-03-08 21:51 UTC

**Comment by TheRealDannyyy** [comment] 2019-03-08 22:06
Can reproduce as well. Will create a bug report there.
Thanks for your time!

**Comment by MJRLegends** [comment] 2019-03-08 22:24
No problem, let me know if you get any more issues with anything
