### ISSUE TITLE
[1.7.10] Nuclear bombs explode on break

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#474] opened 2019-09-01 22:59 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
Naturally spawned nuclear bombs on saturn explode when broken.

### Steps to Reproduce Issue
1. Install latest (2.1.2) version of Extraplanets along with latest galacticraft/Micdoodlecore
2. Travel to saturn and break a nuclear explosive within slime blocks

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
No crash

**Screenshots (if applicable):** 
Can post before and after of exploded area if needed

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.7.10-2.1.2

**Where did this bug happen:** [Single Player or Server]
Both

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment] 2019-09-12 00:47
Seems i did they by design, not sure if i should keep it tbh

**Comment by MJRLegends** [comment] 2019-09-15 20:45
Sure im removing it

**Comment by MJRLegends** [comment] 2019-09-15 21:06
Did you use a pickaxe to break it?

**Comment by MJRLegends** [comment] 2019-09-15 21:11
Turns out its a bug yea. none intended thing :D Will be fixed in next 1.7.10 version :D

**Comment by MJRLegends** [comment] 2020-01-07 04:25
Update MC 1.7.10 has been released

**Closed by MJRLegends** 2020-01-07 04:25 UTC
Labels: 1.7.10, bug, fixed in next update
