### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by DartzGaming** [MJRLegends/ExtraPlanets#279] opened 2018-04-03 04:24 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
[Description of the issue] This is similar to genisis1234r's post about the Space Station loading screen issue. However, whenever I try to go to any planet/moon in the Game it just produces the "Taking one big leap" Screen and stays there. Such as trying to go to Titans Moon. Most of the time you end up on Uranus's Moon, Oberon. And of course the same issue with the Space Station. This is only in the 1.12.2 update.

### Steps to Reproduce Issue
1. [First step] Launch to space, You'll see the Galaxy Map. (Obviously)
2. [Second step] Attempt to Land on an Planet/Moon.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://gist.github.com/DartzGaming/5da66c87ebf79fb5a4131600a5de10aa

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.12.2

**Where did this bug happen:** [Single Player or Server] Single Player

### Additional Information
[Any other information that may be able to help me with the problem] I did both regular launching of a Rocket aswell as using /dimensiontp.

**Comment by MJRLegends** [comment] 2018-04-03 09:05
You have id conflict probably but since its probably that and you've not include more info im going to close this. If its still a issue let me know and no your issue is not like the space station thing

**Closed by MJRLegends** 2018-04-03 09:05 UTC

**Comment by MJRLegends** [comment] 2018-04-03 09:18
Yeah your log includes the following 

]: Dimension already registered to another mod: unable to register planet dimension -31

**Comment by DartzGaming** [comment] 2018-04-04 04:37
The only thing is I'm only using Galacticraft, MJRLegendsLib, and ExtraPlanets. So I don't exactly know how it's ending up with an registered dimension.

**Comment by MJRLegends** [comment] 2018-04-04 04:38
No idea but by default there is no issues try deleting everything and downloading and starting over

**Comment by DartzGaming** [comment] 2018-04-04 04:40
Already tried that two times so far, I can provide all the versions I'm using if you want, Also I'm having the same issue with the MorePlanets Extra Plugin, can't use the Space Stations

**Comment by MJRLegends** [comment] 2018-04-04 04:41
No idea sorry the issue is on your side

**Comment by DartzGaming** [comment] 2018-04-04 04:41
Alrighty, I'll try to figure out the issue

**Comment by DartzGaming** [comment] 2018-04-04 04:44
could it possibly be the version of Forge I'm using?
