### ISSUE TITLE
compatibility with galaxy space and extra planets

### ISSUE THREAD

**Issue by Vonsu** [MJRLegends/ExtraPlanets#492] opened 2019-11-03 20:50 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue [Description of the issue]
Saturn and Uranus from galaxy space doesn't appear on galaxy map
### Steps to Reproduce Issue
1. [First step] Create/open world
2. [Second step] Open galaxy map

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/57330501/68091717-7fcfb380-fe83-11e9-8471-3d4b631904f9.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.5.8
GalaxySpace-1.12.2-2.0.10
AsmodeusCore-1.12.2-0.0.11
MJRLegendsLib-1.12.2-1.1.9
**Where did this bug happen:** [Single Player or Server]
Singe player
### Additional Information
[Any other information that may be able to help me with the problem]
Jupiter and Neptune form galaxy space appear on galaxy map

**Comment by MJRLegends** [comment] 2019-11-03 20:59
Please post ExtraPlanets and Galaxyspace/their core mod configs and a full log file

**Comment by MJRLegends** [comment] 2019-11-03 21:03
Also a better screenshot of the whole galaxy map

**Comment by Vonsu** [comment] 2019-11-03 21:12
Ok I will do it tomorrow beacuse I'm not at the computer right now

**Comment by Vonsu** [comment] 2019-11-04 15:05
[2019-11-04-1.log](https://github.com/MJRLegends/ExtraPlanets/files/3804543/2019-11-04-1.log)

[ExtraPlanets.cfg.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804544/ExtraPlanets.cfg.txt)

Galaxy space:
[core.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804569/core.txt)
[dimensions.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804570/dimensions.txt)
[energy.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804572/energy.txt)
[schematics.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804573/schematics.txt)
Alpha centauri:
[core.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804581/core.txt)
[dimensions.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804583/dimensions.txt)
Barnards:
[core.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804587/core.txt)
[dimensions.txt](https://github.com/MJRLegends/ExtraPlanets/files/3804588/dimensions.txt)
![image](https://user-images.githubusercontent.com/57330501/68131206-ee148480-ff1c-11e9-87cb-06166d7f8878.png)

**Comment by Vonsu** [comment] 2019-11-04 15:16
log: https://pastebin.com/2T2NfVgi
Extra planets: https://pastebin.com/sma7PLFP
Galaxy space: 
Core: https://pastebin.com/16G0xV9V
Dimensions: https://pastebin.com/cAT52wZ1
Energy: https://pastebin.com/PmqkZj0d
Schematics: https://pastebin.com/4g88P45p
Alpha Centauri: https://pastebin.com/GQN1B5D4
https://pastebin.com/M8Mdbma1
Barnards: https://pastebin.com/Xe6qad25
https://pastebin.com/4RCS6UTz
![image](https://user-images.githubusercontent.com/57330501/68132092-6596e380-ff1e-11e9-8c78-24706ea8f4c4.png)

**Comment by MJRLegends** [comment] 2019-11-04 15:35
Thanks. Since you didnt mention you had other Galacticraft addons as well im going to need all them configs please too

**Comment by Vonsu** [comment] 2019-11-04 16:01
More planets extra: https://pastebin.com/m7HUwxsS
More planets: https://pastebin.com/xsJJAgrk
Zollern galaxy: https://pastebin.com/hCjyJq5B

**Comment by MJRLegends** [comment] 2019-11-04 18:22
Thanks will check later. Now that i got the full picture i can start debugging it.

**Comment by MJRLegends** [comment] 2019-11-12 03:52
Ok the issue is GalaxySpace added their own Saturn and Uranus recently so i need to support this as they dont make support on their side....

**Comment by MJRLegends** [comment] 2019-11-12 03:53
Will be fixed in next update

**Comment by Vonsu** [comment] 2019-11-12 14:58
ok thank you for help

**Closed** 2019-11-22 17:08 UTC
Labels: 1.12.2, bug, compatibility issue, fixed in next update

**Comment by MJRLegends** [comment] 2019-11-28 23:16
Updates released for MC 1.12.2

**Comment by LKAice** [comment] 2021-03-01 10:39
Worked for me with the Versions:

MicdoodleCore-1.12.2-4.0.2.280
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
GalaxySpace-1.12.2-2.0.15
More-Planets-1.12.2-2.2.1-GC280
MorePlanetsExtras-1.12.2-1.0
ExtraPlanets-1.12.2-0.7.2

Copied your Configs and both Saturn and Uranus are on the map.
Thank you so much!!!

**Comment by PrimalGN** [comment] 2021-10-23 05:09
> Updates released for MC 1.12.2

I'm having a similar sort of problem with planet progressions i have the same mods with versions the only problem planet progressions seems to not work with all these addons because in logs it says disable the asmodeuscore galaxy map when i use planet progression with the addons!
