### ISSUE TITLE
The creation of a missile

### ISSUE THREAD

**Issue by den4ik0318** [MJRLegends/ExtraPlanets#94] opened 2017-05-13 10:25 UTC
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** No
### Description of Issue
There is no possibility to create a "new" missiles.

### Steps to Reproduce Issue
1. Set the table on which you created the rocket
2. Insert the drawing of the new missile
3. The window of creating a black-purple color

**Version of Mod using:** 1.10.2

**Comment by MJRLegends** [comment] 2017-05-13 11:48
What Version are you using? And I mean my mods version number not mc version

**Comment by MJRLegends** [comment] 2017-05-13 23:13
As i dont see a issue here
![](https://i.gyazo.com/f6902d674f11e04bf7881264ea4df1dc.png)

Im going to close this issue since i cant reproduce it, i will reopen if you provide details

**Closed by MJRLegends** 2017-05-13 23:13 UTC
