### ISSUE TITLE
[1.8.9/1.10.2] Crashes with Triton Dimension Registery & Config option Lead Ore Generation

### ISSUE THREAD

**Issue by Jacky1356400** [MJRLegends/ExtraPlanets#75] opened 2017-04-07 09:24 UTC
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
I have ExtraPlanets installed in my modpack, tried loading up a world and it just crashed straight away.
Checked crash report and apparently it's a crash with dimension -36 (Triton), so I went to the config and change Triton's dimension ID to an unused one. And the pack crashed on launch.

### Steps to Reproduce Issue
1. Load up a new / existing world with ExtraPlanets on default config
2. Crashes straight away

**Crash log/Log (if applicable):** 
[Crash #1](https://pastebin.com/RBR4gPJW) 
[Crash #2](https://pastebin.com/TrmbajTA)

**Version of Mod using:** 0.1.0-Beta-Build for 1.10.2

### Additional Information
N/A

**Comment by MJRLegends** [comment] 2017-04-07 09:43
This is not a bug you just need to change the dimension id since another mod is using -36

**Comment by MJRLegends** [comment] 2017-04-07 09:45
And the second crash is to do with the ore lead generation being turned off and something erroring in the code which is a bug

**Comment by MJRLegends** [comment] 2017-04-07 09:46
**First crash:** This is not a bug you just need to change the dimension id since another mod is using -36

**Second Crash:** Is to do with the ore lead generation being turned off and something erroring in the code which is a bug

**Comment by Jacky1356400** [comment] 2017-04-07 09:50
Ah right, I see.
For the first crash, I can change the dimension ID for now.
For the second crash, as I wanted to unify every single ores to use Thermal Foundation ones instead, so I'll have to wait for a bugfix update.

**Comment by MJRLegends** [comment] 2017-04-07 09:51
@Jacky1356400 No problem i will have a build out soon for 1.10.2 with the second crash fixed :D

**Comment by Jacky1356400** [comment] 2017-04-07 09:53
Thanks :)

**Comment by MJRLegends** [comment] 2017-04-07 10:10
@Jacky1356400 the MC1.10.2 build has been released to fix this (v0.1.5-Beta-Build).

The MC1.8.9 version with the fix will be out later on

**Comment by Jacky1356400** [comment] 2017-04-07 10:12
Hang on...
Update: No matter what dimension ID I change Triton to (tried lots of them), still crashes and it's all related to Triton dimension. 
[Another crash report, I tried to use ID 236, 100% sure no mods are using that dimension ID and still crashes](https://pastebin.com/PiJL248P)

**Comment by MJRLegends** [comment] 2017-04-07 10:14
@Jacky1356400 Please try with just Galacticraft and my mod

**Comment by MJRLegends** [comment] 2017-04-07 10:21
@Jacky1356400 Please give this one a try
https://www.dropbox.com/s/95v7w0uatlecj6r/ExtraPlanets-0.2.0-Beta-Build.jar?dl=0

**Comment by Jacky1356400** [comment] 2017-04-07 10:38
So... 0.2.0 works with Lead oregen enabled but crashes with that disabled... again.
[Crash report](https://pastebin.com/yHAVDjH7)

**Comment by MJRLegends** [comment] 2017-04-07 10:40
@Jacky1356400 Thats fine i know about that, it will be fixed in the release version of v0.2.0-Beta-Build, its more does the dimension id thing work now?

**Comment by Jacky1356400** [comment] 2017-04-07 10:41
Yes, world loads with default ID. At least that's fixed now.

**Comment by MJRLegends** [comment] 2017-04-07 10:43
@Jacky1356400 ok give it 5 mins and the released v0.2.0-Beta-Build version will be out on curse to fix both issues here

**Comment by Jacky1356400** [comment] 2017-04-07 10:45
Thank you so much. :)

**Comment by MJRLegends** [comment] 2017-04-07 10:50
@Jacky1356400 no problem

Also fixed the config option issue for MC1.8.9 (v0.8.1-Beta-Build), the dimension id issue wasnt a issue for that version :P

**Closed by MJRLegends** 2017-04-07 10:50 UTC
Labels: 1.10.2 Bug, 1.8.9 bug, config related issue, fixed in next update (will close issue when update is out)
