### ISSUE TITLE
[1.12.2 MS3] Crash on startup, while loading game

### ISSUE THREAD

**Issue by PG-Fuury** [MJRLegends/ExtraPlanets#270] opened 2018-03-21 11:25 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
As Title says

### Steps to Reproduce Issue
start up MultiMC profile, MS3 with galacticraft .163 (planets, core and micdoodlecore) 

**Crash log/Log (if applicable):**
https://paste.ee/p/Dof6p

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.2.6
**Where did this bug happen:** Single Player

### Additional Information
fresh download from Twitch launcher, transferred to MultiMC, added/changed mods according to Forge errors

**Comment by wamc2017** [comment] 2018-03-21 11:32
Looks like a dupe of #261
Try updating to 1.12.2-0.3.0 ;)

**Comment by MJRLegends** [comment] 2018-03-21 12:33
Please post crash log with latest ExtraPlanets

**Closed by MJRLegends** 2018-03-21 12:33 UTC
