### ISSUE TITLE
[1.12.2] Crash when loading Jupiter Dungeon

### ISSUE THREAD

**Issue by justinrusso** [MJRLegends/ExtraPlanets#298] opened 2018-05-01 13:26 UTC
### Description of Issue
Player appears to be stuck in a crash loop after loading the chunk containing the boss spawner in a Jupiter dungeon.
Reference: https://github.com/Darkosto/SevTech-Ages/issues/2175

**Crash log/Log (if applicable):**
https://pastebin.com/RL0raUm4

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.3.2

**Where did this bug happen:** [Single Player or Server]
Single Player

**Comment by MJRLegends** [comment] 2018-05-11 17:28
Please see comments over on the Darkosto/SevTech-Ages#2175 issue @justinrusso

**Comment by MJRLegends** [comment] 2018-05-11 18:12
Ok so i can confirm i have tested with a null checker on the line crashing and it works and confirms my idea of the dungeon just not generating correctly 
![2018-05-11_19 03 24](https://user-images.githubusercontent.com/8526321/39939411-1fd49a52-554e-11e8-96b8-25c5ab226193.png)

I have made a pull request to fix this over at here on the GC side of things https://github.com/micdoodle8/Galacticraft/pull/3394

Im going to close this issue since its not needed now that we have found the issue and resolved it hopefully if the pull request is accepted which i cant see why it wouldnt be

Any more comments please post them here Darkosto/SevTech-Ages#2175

**Closed by MJRLegends** 2018-05-11 18:12 UTC
Labels: 1.12.2, needs investigating
