### ISSUE TITLE
Everything is white.

### ISSUE THREAD

**Issue by Gatt06** [MJRLegends/ExtraPlanets#201] opened 2018-01-15 03:29 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[All blocks and items are white. This bug is not happening to me, but my friend.]

### Steps to Reproduce Issue
1. [Be my friend with the issue]
2. [Run Minecraft with the mod]

**Crash log/Log (N/A):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![issue](https://user-images.githubusercontent.com/32237085/34925867-b5b135f0-f971-11e7-89a8-82172c0820d2.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION 1.11.2 0.5.3]

**Where did this bug happen:** [Lan world with Hamachi]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment] 2018-01-15 03:30
I dont see any link to why it would be ExtraPlanets, unless you can show that its ExtraPlanets that is the cause of the issue im going to close this issue in the meantime

**Closed by MJRLegends** 2018-01-15 03:30 UTC

**Comment by Gatt06** [comment] 2018-01-15 03:32
My proof is that this was not happening until he installed this mod.

**Comment by MJRLegends** [comment] 2018-01-15 03:34
All ExtraPlanets stuff in the screenshot works, this is not my issue sorry

**Comment by MJRLegends** [comment] 2018-01-15 03:36
Also
1. Your your friend should of made this issue
2. Your detail on the issue is very basic and poor, which means i cant do anything
3. You need to try to reproduce it with Galacticraft and ExtraPlanets

If all those are met then it will be a bug report that needs to be looked at

**Comment by Gatt06** [comment] 2018-01-15 03:39
We figured out the problem, his game is running out of memory and can't load the textures. We are fixing the issue now.

**Comment by MJRLegends** [comment] 2018-01-15 03:39
Glad you fixed it_
