### ISSUE TITLE
[All Versions] When rotating Rocket, you look like you are Outside of it

### ISSUE THREAD

**Issue by CDAGaming** [MJRLegends/ExtraPlanets#207] opened 2018-01-25 23:13 UTC
### Description of Issue
A fun little thing i found, is that when you rotate your rocket forward or backward, It'll move the rocket but not the player correctly. This can lead to the player appearing to be outside of the rocket in whichever orientation the rockets at (Example would be flying sideways, the players pov would be ouside the rocket sideways)

### Steps to Reproduce Issue
1. Get into a Rocket from ExtraPlanets
2. Steer it forwards or backwards (Not straight up)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ~~1.12.2-0.1.5

**Where did this bug happen:** Single Player and Server

**Screenshots (if applicable):** 
*Onedrive messed up, WIP*

**Comment by MJRLegends** [comment] 2018-01-26 16:35
Confirmed to be a bug in MC 1.12.2 i need to check which other versions are affected

**Comment by CDAGaming** [comment] 2018-01-26 17:21
I also need to check in MorePlanetsExtras // MorePlanets is also effected by this...kinda funny bug

**Comment by CDAGaming** [comment] 2018-01-26 17:23
Weird thing I'd like to know is, can you still attack entities while in that circumstance (Technically since your outside the rocket, I think you might be able to tbh xD)

**Comment by MJRLegends** [comment] 2018-01-26 17:24
@CDAGaming Please keep this issue on topic

**Comment by MJRLegends** [comment] 2018-01-26 17:28
Seems to be a bug in all versions, it will be fixed in next update for all versions

**Comment by CDAGaming** [comment] 2018-01-26 19:09
Much Thanks :D

**Comment by MJRLegends** [comment] 2018-01-27 23:26
Fixed in all versions

**Closed by MJRLegends** 2018-01-27 23:26 UTC
Labels: 1.10.2, 1.11.2, 1.12.2, 1.7.10, 1.8.9, bug, fixed in next update (will close issue when update is out)
